name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ${{ matrix.os }}

    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    # - name: Set up QEMU
    #   run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image identity
      id: image_id
      run: echo ::set-output name=ID::${GITHUB_REPOSITORY,,}

    - name: Publish to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/${{ steps.image_id.outputs.ID }}:${{ steps.get_version.outputs.VERSION }}